CREATE DATABASE IF NOT EXISTS contact;

USE contact;

CREATE TABLE IF NOT EXISTS book_form (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  number VARCHAR(255) NOT NULL,
  issue VARCHAR(255) NOT NULL,
  service VARCHAR(255) NOT NULL,
  dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS contact_form (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
